/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FaqIndexImport } from './routes/faq/index'
import { Route as AdminFaqNewIndexImport } from './routes/admin/faq/new/index'

// Create/Update Routes

const FaqIndexRoute = FaqIndexImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRoute,
} as any)

const AdminFaqNewIndexRoute = AdminFaqNewIndexImport.update({
  id: '/admin/faq/new/',
  path: '/admin/faq/new/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/faq/new/': {
      id: '/admin/faq/new/'
      path: '/admin/faq/new'
      fullPath: '/admin/faq/new'
      preLoaderRoute: typeof AdminFaqNewIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/faq': typeof FaqIndexRoute
  '/admin/faq/new': typeof AdminFaqNewIndexRoute
}

export interface FileRoutesByTo {
  '/faq': typeof FaqIndexRoute
  '/admin/faq/new': typeof AdminFaqNewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/faq/': typeof FaqIndexRoute
  '/admin/faq/new/': typeof AdminFaqNewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/faq' | '/admin/faq/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/faq' | '/admin/faq/new'
  id: '__root__' | '/faq/' | '/admin/faq/new/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  FaqIndexRoute: typeof FaqIndexRoute
  AdminFaqNewIndexRoute: typeof AdminFaqNewIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  FaqIndexRoute: FaqIndexRoute,
  AdminFaqNewIndexRoute: AdminFaqNewIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/faq/",
        "/admin/faq/new/"
      ]
    },
    "/faq/": {
      "filePath": "faq/index.tsx"
    },
    "/admin/faq/new/": {
      "filePath": "admin/faq/new/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
